#ifndef SYSCALLX86_H
# define SYSCALLX86_H

# include "ft_strace.h"

typedef struct	t_syscall_info {
	char		*sysname;
	int			p1;
	int			p2;
	int			p3;
	int			p4;
	int			p5;
	int			p6;
	int			ret;
}				s_syscall_info;

#define SYS64 1
//# define UNKNOWN -1
enum e_types {
UNKNOWN = -1,
INT = 1,
UINT,
UNSIGNED_INT,
SIZE_T,
HEX,
INT_PTR,
CONST_INT_PTR,
UNSIGNED_INT_PTR,
SIZE_T_PTR,
LONG,
UNSIGNED_LONG,
UNSIGNED_LONG_PTR,
CONST_UNSIGNED_LONG_PTR,
U32,
U32_PTR,
U64,
U64_PTR,
VOID_PTR,
VOID_PTR_PTR,
CONST_VOID_PTR,
CONST_VOID_PTR_PTR,
CHAR_PTR,
UNSIGNED_CHAR_PTR,
CONST_CHAR_PTR,
CONST_CHAR_PTR_PTR,
UNSIGNED,
UNSIGNED_PTR,
FD_SET_PTR,
UMODE_T,
TIME_T_PTR,
VARARGS,
OFF_T,
LOFF_T,
LOFF_T_PTR,
DEV,
CLOCKID_T,
PID_T,
UID_T,
GID_T,
QID_T,
UID_T_PTR,
GID_T_PTR,
SIG_HANDLER,
OLD_SIGSET_T,
OLD_SIGSET_T_PTR,
SIGSET_T_PTR,
CONST_SIGSET_T_PTR,
SIGINFO_T_PTR,
CAP_USER_HEADER_T,
CONST_CAP_USER_DATA_T,
AIO_CONTEXT_T,
AIO_CONTEXT_T_PTR,
TIMER_T,
TIMER_T_PTR,
MQD_T,
KEY_SERIAL_T,
CAP_USER_DATA_T,
NR_REQS,
RWL_T,
KEY_T,
UNION_BPF_ATTR_PTR,
STRUCT_TMS_PTR,
STRUCT_USTAT_PTR,
STRUCT_OLD_SIGACTION_PTR,
STRUCT_RLIMIT_PTR,
STRUCT_RUSAGE_PTR,
STRUCT_TIMEVAL_PTR,
STRUCT_TIMEZONE_PTR,
STRUCT_STATFS_PTR,
STRUCT_ITIMERVAL_PTR,
STRUCT_OLD_KERNEL_STAT_PTR,
STRUCT_OLDOLD_UTSNAME_PTR,
STRUCT_UTIMBUF_PTR,
STRUCT_SYSINFO_PTR,
STRUCT_OLD_UTSNAME_PTR,
STRUCT_KERNEL_TIMEX_PTR,
STRUCT_LINUX_DIRENT_PTR,
STRUCT_IOVEC_PTR,
STRUCT_SCHED_PARAM_PTR,
STRUCT_KERNEL_TIMESPEC_PTR,
STRUCT_POLLFD_PTR,
STRUCT_SIGACTION_PTR,
CONST_STRUCT_KERNEL_TIMESPEC_PTR,
CONST_STRUCT_SIGALTSTACK_PTR,
STRUCT_SIGALTSTACK_PTR,
STRUCT_STAT64_PTR,
STRUCT_LINUX_DIRENT64_PTR,
STRUCT_IO_EVENT_PTR,
STRUCT_IOCB_PTR_PTR,
STRUCT_IOCB_PTR,
STRUCT_EPOLL_EVENT_PTR,
STRUCT_SIGEVENT_PTR,
STRUCT_KERNEL_ITIMERSPEC_PTR,
STRUCT_STATFS64_PTR,
STRUCT_MQ_ATTR_PTR,
STRUCT_KEXEC_SEGMENT_PTR,
STRUCT_SIGINFO_PTR,
STRUCT_ROBUST_LIST_HEAD_PTR,
STRUCT_ROBUST_LIST_HEAD_PTR_PTR,
CONST_STRUCT_IOVEC_PTR,
STRUCT_GETCPU_CACHE_PTR,
CONST_STRUCT_KERNEL_ITIMERSPEC_PTR,
STRUCT_PERF_EVENT_ATTR_PTR,
STRUCT_MMSGHDR_PTR,
CONST_STRUCT_RLIMIT64_PTR,
STRUCT_RLIMIT64_PTR,
STRUCT_FILE_HANDLE_PTR,
STRUCT_SCHED_ATTR_PTR,
STRUCT_SOCKADDR_PTR,
STRUCT_USER_MSGHDR_PTR,
STRUCT_STATX_PTR,
STRUCT_STAT_PTR,
STRUCT_MSGBUF_PTR,
STRUCT_MSQID_DS_PTR,
STRUCT_SEMBUF_PTR,
STRUCT_SIGSET,
STRUCT_SHMID_DS_PTR,
STRUCT_RSEQ};

//sussy SIGSET_T_PTR, ioctl 


//according to https://x64.syscall.sh/
static s_syscall_info __attribute__((used)) sysinfo_64[] = {
    {"read", UINT, CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"write", UINT, CONST_CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"open", CONST_CHAR_PTR, INT, UMODE_T, 0, 0, 0, 0},
    {"close", INT, 0, 0, 0, 0, 0, 0},
    {"stat", CONST_CHAR_PTR, STRUCT_STAT_PTR, 0, 0, 0, 0, 0},
    {"fstat", INT, STRUCT_STAT_PTR, 0, 0, 0, 0, 0},
    {"lstat", CONST_CHAR_PTR, STRUCT_STAT_PTR, 0, 0, 0, 0, 0},
    {"poll", STRUCT_POLLFD_PTR, UINT, INT, 0, 0, 0, 0},
    {"lseek", INT, OFF_T, INT, 0, 0, 0, 0},
    {"mmap", VOID_PTR, SIZE_T, INT, INT, INT, OFF_T, 1},
    {"mprotect", VOID_PTR, SIZE_T, INT, 0, 0, 0, 0},
    {"munmap", VOID_PTR, SIZE_T, 0, 0, 0, 0, 0},
    {"brk", VOID_PTR, 0, 0, 0, 0, 0, 1},
    {"rt_sigaction", INT, STRUCT_SIGACTION_PTR, STRUCT_SIGACTION_PTR, 0, 0, 0, 0},
    {"rt_sigprocmask", INT, STRUCT_SIGSET, STRUCT_SIGSET, 0, 0, 0, 0},
    {"rt_sigreturn", UNSIGNED_LONG, 0, 0, 0, 0, 0, 0},
    {"ioctl", INT, UNSIGNED_LONG, VARARGS, 0, 0, 0, 0},
    {"pread64", INT, CHAR_PTR, SIZE_T, OFF_T, 0, 0, 0},
    {"pwrite64", INT, CHAR_PTR, SIZE_T, OFF_T, 0, 0, 0},
    {"readv", UINT, STRUCT_IOVEC_PTR, INT, 0, 0, 0, 0},
    {"writev", UINT, STRUCT_IOVEC_PTR, INT, 0, 0, 0, 0},
    {"access", CHAR_PTR, INT, 0, 0, 0, 0, 0},
    {"pipe", INT_PTR, 0, 0, 0, 0, 0, 0},
	{"select", INT, FD_SET_PTR, FD_SET_PTR, FD_SET_PTR, STRUCT_TIMEVAL_PTR, 0, 0},
    {"sched_yield", 0, 0, 0, 0, 0, 0, 0},
    {"mremap", VOID_PTR, SIZE_T, SIZE_T, INT, VARARGS, 0, 0},
    {"msync", VOID_PTR, SIZE_T, INT, 0, 0, 0, 0},
    {"mincore", VOID_PTR, SIZE_T, CHAR_PTR, 0, 0, 0, 0},
    {"madvise", VOID_PTR, SIZE_T, INT, 0, 0, 0, 0},
    {"shmget", KEY_T, SIZE_T, INT, 0, 0, 0, 0},
    {"shmat", INT, CHAR_PTR, INT, 0, 0, 0, 0},
	{"shmctl", INT, INT, STRUCT_SHMID_DS_PTR, INT, 0, 0, 0},
    {"dup", UINT, 0, 0, 0, 0, 0, 0},
    {"dup2", UINT, UINT, 0, 0, 0, 0, 0},
    {"pause", 0, 0, 0, 0, 0, 0, 0},
    {"nanosleep", STRUCT_KERNEL_TIMESPEC_PTR, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0, 0, 0},
    {"getitimer", INT, STRUCT_ITIMERVAL_PTR, 0, 0, 0, 0, 0},
    {"alarm", UINT, 0, 0, 0, 0, 0, 0},
    {"setitimer", INT, STRUCT_ITIMERVAL_PTR, STRUCT_ITIMERVAL_PTR, 0, 0, 0, 0},
    {"getpid", 0, 0, 0, 0, 0, 0, 0},
    {"sendfile", INT, INT, LOFF_T_PTR, SIZE_T, 0, 0, 0},
    {"socket", INT, INT, INT, 0, 0, 0, 0},
    {"connect", INT, STRUCT_SOCKADDR_PTR, INT, 0, 0, 0, 0},
    {"accept", INT, STRUCT_SOCKADDR_PTR, INT_PTR, 0, 0, 0, 0},
    {"sendto", INT, VOID_PTR, SIZE_T, UNSIGNED, STRUCT_SOCKADDR_PTR, INT, 0},
    {"recvfrom", INT, VOID_PTR, SIZE_T, UNSIGNED, STRUCT_SOCKADDR_PTR, INT_PTR, 0},
    {"sendmsg", INT, STRUCT_USER_MSGHDR_PTR, UNSIGNED, 0, 0, 0, 0},
    {"recvmsg", INT, STRUCT_USER_MSGHDR_PTR, UNSIGNED, 0, 0, 0, 0},
    {"shutdown", INT, INT, 0, 0, 0, 0, 0},
    {"bind", INT, STRUCT_SOCKADDR_PTR, INT, 0, 0, 0, 0},
    {"listen", INT, INT, 0, 0, 0, 0, 0},
    {"getsockname", INT, STRUCT_SOCKADDR_PTR, INT_PTR, 0, 0, 0, 0},
    {"getpeername", INT, STRUCT_SOCKADDR_PTR, INT_PTR, 0, 0, 0, 0},
    {"socketpair", INT, INT, INT, INT_PTR, 0, 0, 0},
    {"setsockopt", INT, INT, INT, CHAR_PTR, INT, 0, 0},
    {"getsockopt", INT, INT, INT, CHAR_PTR, INT_PTR, 0, 0},
    {"clone", UNSIGNED_LONG, UNSIGNED_LONG, INT_PTR, INT_PTR, UNSIGNED_LONG, 0, 0},
    {"fork", 0, 0, 0, 0, 0, 0, 0},
    {"vfork", 0, 0, 0, 0, 0, 0, 0},
    {"execve", CONST_CHAR_PTR, CONST_CHAR_PTR_PTR, CONST_CHAR_PTR_PTR, 0, 0, 0, 0},
    {"exit", INT, 0, 0, 0, 0, 0, 0},
	{"wait4", PID_T, INT_PTR, INT, STRUCT_RUSAGE_PTR, 0, 0, 0},
    {"kill", PID_T, INT, 0, 0, 0, 0, 0},
    {"uname", STRUCT_OLD_UTSNAME_PTR, 0, 0, 0, 0, 0, 0},
    {"semget", KEY_T, INT, INT, 0, 0, 0, 0},
    {"semop", INT, STRUCT_SEMBUF_PTR, UNSIGNED, 0, 0, 0, 0},
    {"semctl", INT, INT, INT, UNSIGNED_LONG, 0, 0, 0},
    {"shmdt", CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"msgget", KEY_T, INT, 0, 0, 0, 0, 0},
    {"msgsnd", INT, STRUCT_MSGBUF_PTR, SIZE_T, INT, 0, 0, 0},
    {"msgrcv", INT, STRUCT_MSGBUF_PTR, SIZE_T, LONG, INT, 0, 0},
    {"msgctl", INT, INT, STRUCT_MSQID_DS_PTR, 0, 0, 0, 0},
    {"fcntl", UINT, UINT, UNSIGNED_LONG, 0, 0, 0, 0},
    {"flock", UINT, UINT, 0, 0, 0, 0, 0},
    {"fsync", UINT, 0, 0, 0, 0, 0, 0},
    {"fdatasync", UINT, 0, 0, 0, 0, 0, 0},
    {"truncate", CONST_CHAR_PTR, LONG, 0, 0, 0, 0, 0},
    {"ftruncate", UINT, UNSIGNED_LONG, 0, 0, 0, 0, 0},
    {"getdents", UINT, STRUCT_LINUX_DIRENT_PTR, UINT, 0, 0, 0, 0},
    {"getcwd", CHAR_PTR, UNSIGNED_LONG, 0, 0, 0, 0, 0},
    {"chdir", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"fchdir", UINT, 0, 0, 0, 0, 0, 0},
    {"rename", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"mkdir", CONST_CHAR_PTR, UMODE_T, 0, 0, 0, 0, 0},
    {"rmdir", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"creat", CONST_CHAR_PTR, UMODE_T, 0, 0, 0, 0, 0},
    {"link", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"unlink", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"symlink", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"readlink", CONST_CHAR_PTR, CHAR_PTR, INT, 0, 0, 0, 0},
    {"chmod", CONST_CHAR_PTR, UMODE_T, 0, 0, 0, 0, 0},
    {"fchmod", UINT, UMODE_T, 0, 0, 0, 0, 0},
    {"chown", CONST_CHAR_PTR, UID_T, GID_T, 0, 0, 0, 0},
    {"fchown", UINT, UID_T, GID_T, 0, 0, 0, 0},
    {"lchown", CONST_CHAR_PTR, UID_T, GID_T, 0, 0, 0, 0},
    {"umask", INT, 0, 0, 0, 0, 0, 0},
    {"gettimeofday", STRUCT_TIMEVAL_PTR, STRUCT_TIMEZONE_PTR, 0, 0, 0, 0, 0},
    {"getrlimit", UINT, STRUCT_RLIMIT_PTR, 0, 0, 0, 0, 0},
    {"getrusage", INT, STRUCT_RUSAGE_PTR, 0, 0, 0, 0, 0},
    {"sysinfo", STRUCT_SYSINFO_PTR, 0, 0, 0, 0, 0, 0},
    {"times", STRUCT_TMS_PTR, 0, 0, 0, 0, 0, 0},
    {"ptrace", LONG, LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0, 0},
    {"getuid", 0, 0, 0, 0, 0, 0, 0},
    {"syslog", INT, CHAR_PTR, INT, 0, 0, 0, 0},
    {"getgid", 0, 0, 0, 0, 0, 0, 0},
    {"setuid", UID_T, 0, 0, 0, 0, 0, 0},
    {"setgid", GID_T, 0, 0, 0, 0, 0, 0},
    {"geteuid", 0, 0, 0, 0, 0, 0, 0},
    {"getegid", 0, 0, 0, 0, 0, 0, 0},
    {"setpgid", PID_T, PID_T, 0, 0, 0, 0, 0},
    {"getppid", 0, 0, 0, 0, 0, 0, 0},
    {"getpgrp", 0, 0, 0, 0, 0, 0, 0},
    {"setsid", 0, 0, 0, 0, 0, 0, 0},
    {"setreuid", UID_T, UID_T, 0, 0, 0, 0, 0},
    {"setregid", GID_T, GID_T, 0, 0, 0, 0, 0},
    {"getgroups", INT, GID_T_PTR, 0, 0, 0, 0, 0},
    {"setgroups", INT, GID_T_PTR, 0, 0, 0, 0, 0},
    {"setresuid", UID_T, UID_T, UID_T, 0, 0, 0, 0},
    {"getresuid", UID_T_PTR, UID_T_PTR, UID_T_PTR, 0, 0, 0, 0},
    {"setresgid", GID_T, GID_T, GID_T, 0, 0, 0, 0},
    {"getresgid", GID_T_PTR, GID_T_PTR, GID_T_PTR, 0, 0, 0, 0},
	{"getpgid", PID_T, 0, 0, 0, 0, 0, 0},
    {"setfsuid", UID_T, 0, 0, 0, 0, 0, 0},
    {"setfsgid", GID_T, 0, 0, 0, 0, 0, 0},
    {"getsid", PID_T, 0, 0, 0, 0, 0, 0},
    {"capget", CAP_USER_HEADER_T, CAP_USER_DATA_T, 0, 0, 0, 0, 0},
    {"capset", CAP_USER_HEADER_T, CONST_CAP_USER_DATA_T, 0, 0, 0, 0, 0},
    {"rt_sigpending", SIGSET_T_PTR, SIZE_T, 0, 0, 0, 0, 0},
    {"rt_sigtimedwait", CONST_SIGSET_T_PTR, SIGINFO_T_PTR, CONST_STRUCT_KERNEL_TIMESPEC_PTR, SIZE_T, 0, 0, 0},
    {"rt_sigqueueinfo", PID_T, INT, SIGINFO_T_PTR, 0, 0, 0, 0},
    {"rt_sigsuspend", SIGSET_T_PTR, SIZE_T, 0, 0, 0, 0, 0},
    {"sigaltstack", CONST_STRUCT_SIGALTSTACK_PTR, STRUCT_SIGALTSTACK_PTR, 0, 0, 0, 0, 0},
    {"utime", CHAR_PTR, STRUCT_UTIMBUF_PTR, 0, 0, 0, 0, 0},
    {"mknod", CONST_CHAR_PTR, UMODE_T, UNSIGNED, 0, 0, 0, 0},
    {"uselib", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"personality", UINT, 0, 0, 0, 0, 0, 0},
    {"ustat", UNSIGNED, STRUCT_USTAT_PTR, 0, 0, 0, 0, 0},
    {"statfs", CONST_CHAR_PTR, STRUCT_STATFS_PTR, 0, 0, 0, 0, 0},
    {"fstatfs", UINT, STRUCT_STATFS_PTR, 0, 0, 0, 0, 0},
    {"sysfs", INT, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0, 0, 0},
    {"getpriority", INT, INT, 0, 0, 0, 0, 0},
    {"setpriority", INT, INT, INT, 0, 0, 0, 0},
    {"sched_setparam", PID_T, STRUCT_SCHED_PARAM_PTR, 0, 0, 0, 0, 0},
    {"sched_getparam", PID_T, STRUCT_SCHED_PARAM_PTR, 0, 0, 0, 0, 0},
    {"sched_setscheduler", PID_T, INT, STRUCT_SCHED_PARAM_PTR, 0, 0, 0, 0},
    {"sched_getscheduler", PID_T, 0, 0, 0, 0, 0, 0},
    {"sched_get_priority_max", INT, 0, 0, 0, 0, 0, 0},
    {"sched_get_priority_min", INT, 0, 0, 0, 0, 0, 0},
    {"sched_rr_get_interval", PID_T, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0, 0, 0},
    {"mlock", UNSIGNED_LONG, SIZE_T, 0, 0, 0, 0, 0},
    {"munlock", UNSIGNED_LONG, SIZE_T, 0, 0, 0, 0, 0},
	{"mlockall", INT, 0, 0, 0, 0, 0, 0},
    {"munlockall", 0, 0, 0, 0, 0, 0, 0},
    {"vhangup", 0, 0, 0, 0, 0, 0, 0},
    {"modify_ldt", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"pivot_root", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"_sysctl", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"prctl", INT, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"arch_prctl", UNKNOWN, UNKNOWN, 0, 0, 0, 0, 0},
    {"adjtimex", STRUCT_KERNEL_TIMEX_PTR, 0, 0, 0, 0, 0, 0},
    {"setrlimit", UINT, STRUCT_RLIMIT_PTR, 0, 0, 0, 0, 0},
    {"chroot", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"sync", 0, 0, 0, 0, 0, 0, 0},
    {"acct", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"settimeofday", STRUCT_TIMEVAL_PTR, STRUCT_TIMEZONE_PTR, 0, 0, 0, 0, 0},
    {"mount", CHAR_PTR, CHAR_PTR, CHAR_PTR, UNSIGNED_LONG, VOID_PTR, 0, 0},
    {"umount2", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"swapon", CONST_CHAR_PTR, INT, 0, 0, 0, 0, 0},
    {"swapoff", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"reboot", INT, INT, UINT, VOID_PTR, 0, 0, 0},
    {"sethostname", CHAR_PTR, INT, 0, 0, 0, 0, 0},
    {"setdomainname", CHAR_PTR, INT, 0, 0, 0, 0, 0},
    {"iopl", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"ioperm", UNSIGNED_LONG, UNSIGNED_LONG, INT, 0, 0, 0, 0},
    {"create_module", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"init_module", VOID_PTR, UNSIGNED_LONG, CONST_CHAR_PTR, 0, 0, 0, 0},
    {"delete_module", CONST_CHAR_PTR, UINT, 0, 0, 0, 0, 0},
    {"get_kernel_syms", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"query_module", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"quotactl", UINT, CONST_CHAR_PTR, QID_T, VOID_PTR, 0, 0, 0},
	{"nfsservctl", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"getpmsg", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"putpmsg", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"afs_syscall", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"tuxcall", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"security", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"gettid", 0, 0, 0, 0, 0, 0, 0},
    {"readahead", INT, LOFF_T, SIZE_T, 0, 0, 0, 0},
    {"setxattr", CONST_CHAR_PTR, CONST_CHAR_PTR, CONST_VOID_PTR, SIZE_T, INT, 0, 0},
    {"lsetxattr", CONST_CHAR_PTR, CONST_CHAR_PTR, CONST_VOID_PTR, SIZE_T, INT, 0, 0},
    {"fsetxattr", INT, CONST_CHAR_PTR, CONST_VOID_PTR, SIZE_T, INT, 0, 0},
    {"getxattr", CONST_CHAR_PTR, CONST_CHAR_PTR, VOID_PTR, SIZE_T, 0, 0, 0},
    {"lgetxattr", CONST_CHAR_PTR, CONST_CHAR_PTR, VOID_PTR, SIZE_T, 0, 0, 0},
    {"fgetxattr", INT, CONST_CHAR_PTR, VOID_PTR, SIZE_T, 0, 0, 0},
    {"listxattr", CONST_CHAR_PTR, CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"llistxattr", CONST_CHAR_PTR, CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"flistxattr", INT, CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"removexattr", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"lremovexattr", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"fremovexattr", INT, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"tkill", PID_T, INT, 0, 0, 0, 0, 0},
    {"time", TIME_T_PTR, 0, 0, 0, 0, 0, 0},
    {"futex", U32_PTR, INT, U32, STRUCT_KERNEL_TIMESPEC_PTR, U32_PTR, U32, 0},
    {"sched_setaffinity", PID_T, UINT, UNSIGNED_LONG_PTR, 0, 0, 0, 0},
    {"sched_getaffinity", PID_T, UINT, UNSIGNED_LONG_PTR, 0, 0, 0, 0},
    {"set_thread_area", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"io_setup", UNSIGNED, AIO_CONTEXT_T_PTR, 0, 0, 0, 0, 0},
    {"io_destroy", AIO_CONTEXT_T, 0, 0, 0, 0, 0, 0},
    {"io_getevents", AIO_CONTEXT_T, LONG, LONG, STRUCT_IO_EVENT_PTR, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0},
    {"io_submit", AIO_CONTEXT_T, LONG, STRUCT_IOCB_PTR_PTR, 0, 0, 0, 0},
    {"io_cancel", AIO_CONTEXT_T, STRUCT_IOCB_PTR, STRUCT_IO_EVENT_PTR, 0, 0, 0, 0},
	{"get_thread_area", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"lookup_dcookie", U64, CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"epoll_create", INT, 0, 0, 0, 0, 0, 0},
    {"epoll_ctl_old", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"epoll_wait_old", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"remap_file_pages", UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"getdents64", UINT, STRUCT_LINUX_DIRENT64_PTR, UINT, 0, 0, 0, 0},
    {"set_tid_address", INT_PTR, 0, 0, 0, 0, 0, 0},
    {"restart_syscall", 0, 0, 0, 0, 0, 0, 0},
    {"semtimedop", INT, STRUCT_SEMBUF_PTR, UNSIGNED, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0},
    {"fadvise64", INT, LOFF_T, SIZE_T, INT, 0, 0, 0},
    {"timer_create", CLOCKID_T, STRUCT_SIGEVENT_PTR, TIMER_T_PTR, 0, 0, 0, 0},
    {"timer_settime", TIMER_T, INT, STRUCT_KERNEL_ITIMERSPEC_PTR, STRUCT_KERNEL_ITIMERSPEC_PTR, 0, 0, 0},
    {"timer_gettime", TIMER_T, STRUCT_KERNEL_ITIMERSPEC_PTR, 0, 0, 0, 0, 0},
    {"timer_getoverrun", TIMER_T, 0, 0, 0, 0, 0, 0},
    {"timer_delete", TIMER_T, 0, 0, 0, 0, 0, 0},
    {"clock_settime", CLOCKID_T, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0, 0, 0},
    {"clock_gettime", CLOCKID_T, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0, 0, 0},
    {"clock_getres", CLOCKID_T, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0, 0, 0},
    {"clock_nanosleep", CLOCKID_T, INT, STRUCT_KERNEL_TIMESPEC_PTR, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0},
    {"exit_group", INT, 0, 0, 0, 0, 0, 0},
    {"epoll_wait", INT, STRUCT_EPOLL_EVENT_PTR, INT, INT, 0, 0, 0},
    {"epoll_ctl", INT, INT, INT, STRUCT_EPOLL_EVENT_PTR, 0, 0, 0},
    {"tgkill", PID_T, PID_T, INT, 0, 0, 0, 0},
    {"utimes", CHAR_PTR, STRUCT_TIMEVAL_PTR, 0, 0, 0, 0, 0},
    {"vserver", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"mbind", UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG_PTR, UNSIGNED_LONG, UNSIGNED, 0},
    {"set_mempolicy", INT, UNSIGNED_LONG_PTR, UNSIGNED_LONG, 0, 0, 0, 0},
    {"get_mempolicy", INT_PTR, UNSIGNED_LONG_PTR, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"mq_open", CONST_CHAR_PTR, INT, UMODE_T, STRUCT_MQ_ATTR_PTR, 0, 0, 0},
	{"mq_unlink", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"mq_timedsend", MQD_T, CONST_CHAR_PTR, SIZE_T, UINT, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0},
    {"mq_timedreceive", MQD_T, CHAR_PTR, SIZE_T, UNSIGNED_INT_PTR, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0},
    {"mq_notify", MQD_T, STRUCT_SIGEVENT_PTR, 0, 0, 0, 0, 0},
    {"mq_getsetattr", MQD_T, STRUCT_MQ_ATTR_PTR, STRUCT_MQ_ATTR_PTR, 0, 0, 0, 0},
    {"kexec_load", UNSIGNED_LONG, UNSIGNED_LONG, STRUCT_KEXEC_SEGMENT_PTR, UNSIGNED_LONG, 0, 0, 0},
    {"waitid", INT, PID_T, STRUCT_SIGINFO_PTR, INT, STRUCT_RUSAGE_PTR, 0, 0},
    {"add_key", CONST_CHAR_PTR, CONST_CHAR_PTR, CONST_VOID_PTR, SIZE_T, KEY_SERIAL_T, 0, 0},
    {"request_key", CONST_CHAR_PTR, CONST_CHAR_PTR, CONST_CHAR_PTR, KEY_SERIAL_T, 0, 0, 0},
    {"keyctl", INT, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"ioprio_set", INT, INT, INT, 0, 0, 0, 0},
    {"ioprio_get", INT, INT, 0, 0, 0, 0, 0},
    {"inotify_init", 0, 0, 0, 0, 0, 0, 0},
    {"inotify_add_watch", INT, CONST_CHAR_PTR, INT, 0, 0, 0, 0},
    {"inotify_rm_watch", INT, INT, 0, 0, 0, 0, 0},
    {"migrate_pages", PID_T, UNSIGNED_LONG, UNSIGNED_LONG_PTR, UNSIGNED_LONG_PTR, 0, 0, 0},
    {"openat", INT, CONST_CHAR_PTR, INT, UMODE_T, 0, 0, 0},
    {"mkdirat", INT, CONST_CHAR_PTR, UMODE_T, 0, 0, 0, 0},
    {"mknodat", INT, CONST_CHAR_PTR, UMODE_T, UNSIGNED, 0, 0, 0},
    {"fchownat", INT, CONST_CHAR_PTR, UID_T, GID_T, INT, 0, 0},
    {"futimesat", INT, CONST_CHAR_PTR, STRUCT_TIMEVAL_PTR, 0, 0, 0, 0},
    {"newfstatat", INT, CONST_CHAR_PTR, STRUCT_STAT_PTR, INT, 0, 0, 0},
    {"unlinkat", INT, CONST_CHAR_PTR, INT, 0, 0, 0, 0},
    {"renameat", INT, CONST_CHAR_PTR, INT, CONST_CHAR_PTR, 0, 0, 0},
    {"linkat", INT, CONST_CHAR_PTR, INT, CONST_CHAR_PTR, INT, 0, 0},
    {"symlinkat", CONST_CHAR_PTR, INT, CONST_CHAR_PTR, 0, 0, 0, 0},
    {"readlinkat", INT, CONST_CHAR_PTR, CHAR_PTR, INT, 0, 0, 0},
    {"fchmodat", INT, CONST_CHAR_PTR, UMODE_T, 0, 0, 0, 0},
    {"faccessat", INT, CONST_CHAR_PTR, INT, 0, 0, 0, 0},
    {"pselect6", INT, FD_SET_PTR, FD_SET_PTR, FD_SET_PTR, STRUCT_KERNEL_TIMESPEC_PTR, VOID_PTR, 0},
	{"ppoll", STRUCT_POLLFD_PTR, UINT, STRUCT_KERNEL_TIMESPEC_PTR, SIGSET_T_PTR, SIZE_T, 0, 0},
    {"unshare", UNSIGNED_LONG, 0, 0, 0, 0, 0, 0},
    {"set_robust_list", STRUCT_ROBUST_LIST_HEAD_PTR, SIZE_T, 0, 0, 0, 0, 0},
    {"get_robust_list", INT, STRUCT_ROBUST_LIST_HEAD_PTR_PTR, SIZE_T_PTR, 0, 0, 0, 0},
    {"splice", INT, LOFF_T_PTR, INT, LOFF_T_PTR, SIZE_T, UINT, 0},
    {"tee", INT, INT, SIZE_T, UINT, 0, 0, 0},
    {"sync_file_range", INT, LOFF_T, LOFF_T, UINT, 0, 0, 0},
    {"vmsplice", INT, STRUCT_IOVEC_PTR, UNSIGNED_LONG, UINT, 0, 0, 0},
    {"move_pages", PID_T, UNSIGNED_LONG, VOID_PTR_PTR, INT_PTR, INT_PTR, INT, 0},
    {"utimensat", INT, CONST_CHAR_PTR, STRUCT_KERNEL_TIMESPEC_PTR, INT, 0, 0, 0},
    {"epoll_pwait", INT, STRUCT_EPOLL_EVENT_PTR, INT, INT, SIGSET_T_PTR, SIZE_T, 0},
    {"signalfd", INT, SIGSET_T_PTR, SIZE_T, 0, 0, 0, 0},
    {"timerfd_create", INT, INT, 0, 0, 0, 0, 0},
    {"eventfd", UINT, 0, 0, 0, 0, 0, 0},
    {"fallocate", INT, INT, LOFF_T, LOFF_T, 0, 0, 0},
    {"timerfd_settime", INT, INT, STRUCT_KERNEL_ITIMERSPEC_PTR, STRUCT_KERNEL_ITIMERSPEC_PTR, 0, 0, 0},
    {"timerfd_gettime", INT, STRUCT_KERNEL_ITIMERSPEC_PTR, 0, 0, 0, 0, 0},
    {"accept4", INT, STRUCT_SOCKADDR_PTR, INT_PTR, INT, 0, 0, 0},
    {"signalfd4", INT, SIGSET_T_PTR, SIZE_T, INT, 0, 0, 0},
    {"eventfd2", UINT, INT, 0, 0, 0, 0, 0},
    {"epoll_create1", INT, 0, 0, 0, 0, 0, 0},
    {"dup3", UINT, UINT, INT, 0, 0, 0, 0},
    {"pipe2", INT_PTR, INT, 0, 0, 0, 0, 0},
    {"inotify_init1", INT, 0, 0, 0, 0, 0, 0},
    {"preadv", UNSIGNED_LONG, STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"pwritev", UNSIGNED_LONG, STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"rt_tgsigqueueinfo", PID_T, PID_T, INT, SIGINFO_T_PTR, 0, 0, 0},
    {"perf_event_open", STRUCT_PERF_EVENT_ATTR_PTR, PID_T, INT, INT, UNSIGNED_LONG, 0, 0},
    {"recvmmsg", INT, STRUCT_MMSGHDR_PTR, UINT, UNSIGNED, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0},
    {"fanotify_init", UINT, UINT, 0, 0, 0, 0, 0},
	{"fanotify_mark", INT, UINT, U64, INT, CONST_CHAR_PTR, 0, 0},
    {"prlimit64", PID_T, UINT, STRUCT_RLIMIT64_PTR, STRUCT_RLIMIT64_PTR, 0, 0, 0},
    {"name_to_handle_at", INT, CONST_CHAR_PTR, STRUCT_FILE_HANDLE_PTR, INT_PTR, INT, 0, 0},
    {"open_by_handle_at", INT, STRUCT_FILE_HANDLE_PTR, INT, 0, 0, 0, 0},
    {"clock_adjtime", CLOCKID_T, STRUCT_KERNEL_TIMEX_PTR, 0, 0, 0, 0, 0},
    {"syncfs", INT, 0, 0, 0, 0, 0, 0},
    {"sendmmsg", INT, STRUCT_MMSGHDR_PTR, UINT, UNSIGNED, 0, 0, 0},
    {"setns", INT, INT, 0, 0, 0, 0, 0},
    {"getcpu", UNSIGNED_PTR, UNSIGNED_PTR, STRUCT_GETCPU_CACHE_PTR, 0, 0, 0, 0},
    {"process_vm_readv", PID_T, STRUCT_IOVEC_PTR, UNSIGNED_LONG, STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, 0},
    {"process_vm_writev", PID_T, STRUCT_IOVEC_PTR, UNSIGNED_LONG, STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, 0},
    {"kcmp", PID_T, PID_T, INT, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"finit_module", INT, CONST_CHAR_PTR, INT, 0, 0, 0, 0},
    {"sched_setattr", PID_T, STRUCT_SCHED_ATTR_PTR, UINT, 0, 0, 0, 0},
    {"sched_getattr", PID_T, STRUCT_SCHED_ATTR_PTR, UINT, UINT, 0, 0, 0},
    {"renameat2", INT, CONST_CHAR_PTR, INT, CONST_CHAR_PTR, UINT, 0, 0},
    {"seccomp", UINT, UINT, VOID_PTR, 0, 0, 0, 0},
    {"getrandom", VOID_PTR, SIZE_T, UINT, 0, 0, 0, 0},
    {"memfd_create", CONST_CHAR_PTR, UINT, 0, 0, 0, 0, 0},
    {"kexec_file_load", INT, INT, UNSIGNED_LONG, CONST_CHAR_PTR, UNSIGNED_LONG, 0, 0},
    {"bpf", INT, UNION_BPF_ATTR_PTR, UINT, 0, 0, 0, 0},
    {"execveat", INT, CONST_CHAR_PTR, CONST_CHAR_PTR_PTR, CONST_CHAR_PTR_PTR, INT, 0, 0},
    {"userfaultfd", INT, 0, 0, 0, 0, 0, 0},
    {"membarrier", INT, INT, 0, 0, 0, 0, 0},
    {"mlock2", UNSIGNED_LONG, SIZE_T, INT, 0, 0, 0, 0},
    {"copy_file_range", INT, LOFF_T_PTR, INT, LOFF_T_PTR, SIZE_T, UINT, 0},
    {"preadv2", UNSIGNED_LONG, STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, RWL_T, 0},
    {"pwritev2", UNSIGNED_LONG, STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, RWL_T, 0},
    {"pkey_mprotect", UNSIGNED_LONG, SIZE_T, UNSIGNED_LONG, INT, 0, 0, 0},
    {"pkey_alloc", UNSIGNED_LONG, UNSIGNED_LONG, 0, 0, 0, 0, 0},
    {"pkey_free", INT, 0, 0, 0, 0, 0, 0},
    {"statx", INT, CONST_CHAR_PTR, UNSIGNED, UNSIGNED, STRUCT_STATX_PTR, 0, 0},
	{"io_pgetevents", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
	{"rseq", STRUCT_RSEQ, U32, INT, HEX, 0, 0, 0}
};

static s_syscall_info __attribute__((used)) sysinfo_32[] = {
    {"restart_syscall", 0, 0, 0, 0, 0, 0, 0},
    {"exit", INT, 0, 0, 0, 0, 0, 0},
    {"fork", 0, 0, 0, 0, 0, 0, 0},
    {"read", UNSIGNED_INT, CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"write", UNSIGNED_INT, CONST_CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"open", CONST_CHAR_PTR, INT, UMODE_T, 0, 0, 0, 0},
    {"close", UNSIGNED_INT, 0, 0, 0, 0, 0, 0},
    {"waitpid", PID_T, INT_PTR, INT, 0, 0, 0, 0},
    {"creat", CONST_CHAR_PTR, UMODE_T, 0, 0, 0, 0, 0},
    {"link", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"unlink", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"execve", CONST_CHAR_PTR, CONST_CHAR_PTR_PTR, CONST_CHAR_PTR_PTR, 0, 0, 0, 0},
    {"chdir", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"time", TIME_T_PTR, 0, 0, 0, 0, 0, 0},
    {"mknod", CONST_CHAR_PTR, UMODE_T, UNSIGNED, 0, 0, 0, 0},
    {"chmod", CONST_CHAR_PTR, UMODE_T, 0, 0, 0, 0, 0},
    {"lchown", CONST_CHAR_PTR, UID_T, GID_T, 0, 0, 0, 0},
    {"break", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"oldstat", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"lseek", UNSIGNED_INT, OFF_T, UNSIGNED_INT, 0, 0, 0, 0},
    {"getpid", 0, 0, 0, 0, 0, 0, 0},
    {"mount", CHAR_PTR, CHAR_PTR, CHAR_PTR, UNSIGNED_LONG, VOID_PTR, 0, 0},
    {"umount", CHAR_PTR, INT, 0, 0, 0, 0, 0},
    {"setuid", UID_T, 0, 0, 0, 0, 0, 0},
    {"getuid", 0, 0, 0, 0, 0, 0, 0},
    {"stime", TIME_T_PTR, 0, 0, 0, 0, 0, 0},
    {"ptrace", LONG, LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0, 0},
    {"alarm", UNSIGNED_INT, 0, 0, 0, 0, 0, 0},
    {"oldfstat", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"pause", 0, 0, 0, 0, 0, 0, 0},
    {"utime", CHAR_PTR, STRUCT_UTIMBUF_PTR, 0, 0, 0, 0, 0},
    {"stty", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"gtty", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"access", CONST_CHAR_PTR, INT, 0, 0, 0, 0, 0},
    {"nice", INT, 0, 0, 0, 0, 0, 0},
    {"ftime", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"sync", 0, 0, 0, 0, 0, 0, 0},
    {"kill", PID_T, INT, 0, 0, 0, 0, 0},
    {"rename", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"mkdir", CONST_CHAR_PTR, UMODE_T, 0, 0, 0, 0, 0},
    {"rmdir", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"dup", UNSIGNED_INT, 0, 0, 0, 0, 0, 0},
    {"pipe", INT_PTR, 0, 0, 0, 0, 0, 0},
    {"times", STRUCT_TMS_PTR, 0, 0, 0, 0, 0, 0},
    {"prof", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"brk", VOID_PTR, 0, 0, 0, 0, 0, 1},
    {"setgid", GID_T, 0, 0, 0, 0, 0, 0},
    {"getgid", 0, 0, 0, 0, 0, 0, 0},
    {"signal", INT, SIG_HANDLER, 0, 0, 0, 0, 0},
    {"geteuid", 0, 0, 0, 0, 0, 0, 0},
    {"getegid", 0, 0, 0, 0, 0, 0, 0},
	{"acct", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"umount2", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"lock", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"ioctl", UNSIGNED_INT, UNSIGNED_INT, UNSIGNED_LONG, 0, 0, 0, 0},
    {"fcntl", UNSIGNED_INT, UNSIGNED_INT, UNSIGNED_LONG, 0, 0, 0, 0},
    {"mpx", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setpgid", PID_T, PID_T, 0, 0, 0, 0, 0},
    {"ulimit", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"oldolduname", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"umask", INT, 0, 0, 0, 0, 0, 0},
    {"chroot", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"ustat", UNSIGNED, STRUCT_USTAT_PTR, 0, 0, 0, 0, 0},
    {"dup2", UNSIGNED_INT, UNSIGNED_INT, 0, 0, 0, 0, 0},
    {"getppid", 0, 0, 0, 0, 0, 0, 0},
    {"getpgrp", 0, 0, 0, 0, 0, 0, 0},
    {"setsid", 0, 0, 0, 0, 0, 0, 0},
    {"sigaction", INT, STRUCT_OLD_SIGACTION_PTR, STRUCT_OLD_SIGACTION_PTR, 0, 0, 0, 0},
    {"sgetmask", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"ssetmask", INT, 0, 0, 0, 0, 0, 0},
    {"setreuid", UID_T, UID_T, 0, 0, 0, 0, 0},
    {"setregid", GID_T, GID_T, 0, 0, 0, 0, 0},
    {"sigsuspend", INT, INT, OLD_SIGSET_T, 0, 0, 0, 0},
    {"sigpending", OLD_SIGSET_T_PTR, 0, 0, 0, 0, 0, 0},
    {"sethostname", CHAR_PTR, INT, 0, 0, 0, 0, 0},
    {"setrlimit", UNSIGNED_INT, STRUCT_RLIMIT_PTR, 0, 0, 0, 0, 0},
    {"getrlimit", UNSIGNED_INT, STRUCT_RLIMIT_PTR, 0, 0, 0, 0, 0},
    {"getrusage", INT, STRUCT_RUSAGE_PTR, 0, 0, 0, 0, 0},
    {"gettimeofday", STRUCT_TIMEVAL_PTR, STRUCT_TIMEZONE_PTR, 0, 0, 0, 0, 0},
    {"settimeofday", STRUCT_TIMEVAL_PTR, STRUCT_TIMEZONE_PTR, 0, 0, 0, 0, 0},
    {"getgroups", INT, GID_T_PTR, 0, 0, 0, 0, 0},
    {"setgroups", INT, GID_T_PTR, 0, 0, 0, 0, 0},
    {"select", INT, FD_SET_PTR, FD_SET_PTR, FD_SET_PTR, STRUCT_TIMEVAL_PTR, 0, 0},
    {"symlink", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"oldlstat", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"readlink", CONST_CHAR_PTR, CHAR_PTR, INT, 0, 0, 0, 0},
    {"uselib", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"swapon", CONST_CHAR_PTR, INT, 0, 0, 0, 0, 0},
    {"reboot", INT, INT, UNSIGNED_INT, VOID_PTR, 0, 0, 0},
    {"readdir", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"mmap", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 1},
    {"munmap", VOID_PTR, SIZE_T, 0, 0, 0, 0, 0},
    {"truncate", CONST_CHAR_PTR, LONG, 0, 0, 0, 0, 0},
    {"ftruncate", UNSIGNED_INT, UNSIGNED_LONG, 0, 0, 0, 0, 0},
    {"fchmod", UNSIGNED_INT, UMODE_T, 0, 0, 0, 0, 0},
    {"fchown", UNSIGNED_INT, UID_T, GID_T, 0, 0, 0, 0},
    {"getpriority", INT, INT, 0, 0, 0, 0, 0},
    {"setpriority", INT, INT, INT, 0, 0, 0, 0},
    {"profil", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"statfs", CONST_CHAR_PTR, STRUCT_STATFS_PTR, 0, 0, 0, 0, 0},
    {"fstatfs", UNSIGNED_INT, STRUCT_STATFS_PTR, 0, 0, 0, 0, 0},
	{"ioperm", UNSIGNED_LONG, UNSIGNED_LONG, INT, 0, 0, 0, 0},
    {"socketcall", INT, UNSIGNED_LONG_PTR, 0, 0, 0, 0, 0},
    {"syslog", INT, CHAR_PTR, INT, 0, 0, 0, 0},
    {"setitimer", INT, STRUCT_ITIMERVAL_PTR, STRUCT_ITIMERVAL_PTR, 0, 0, 0, 0},
    {"getitimer", INT, STRUCT_ITIMERVAL_PTR, 0, 0, 0, 0, 0},
    {"stat", CONST_CHAR_PTR, STRUCT_OLD_KERNEL_STAT_PTR, 0, 0, 0, 0, 0},
    {"lstat", CONST_CHAR_PTR, STRUCT_OLD_KERNEL_STAT_PTR, 0, 0, 0, 0, 0},
    {"fstat", UNSIGNED_INT, STRUCT_OLD_KERNEL_STAT_PTR, 0, 0, 0, 0, 0},
    {"olduname", STRUCT_OLDOLD_UTSNAME_PTR, 0, 0, 0, 0, 0, 0},
    {"iopl", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"vhangup", 0, 0, 0, 0, 0, 0, 0},
    {"idle", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"vm86old", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"wait4", PID_T, INT_PTR, INT, STRUCT_RUSAGE_PTR, 0, 0, 0},
    {"swapoff", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"sysinfo", STRUCT_SYSINFO_PTR, 0, 0, 0, 0, 0, 0},
    {"ipc", UNSIGNED_INT, INT, UNSIGNED_LONG, UNSIGNED_LONG, VOID_PTR, LONG, 0},
    {"fsync", UNSIGNED_INT, 0, 0, 0, 0, 0, 0},
    {"sigreturn", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"clone", VOID_PTR, VOID_PTR, INT, VOID_PTR, 0, 0, 0},
    {"setdomainname", CHAR_PTR, INT, 0, 0, 0, 0, 0},
    {"uname", STRUCT_OLD_UTSNAME_PTR, 0, 0, 0, 0, 0, 0},
    {"modify_ldt", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"adjtimex", STRUCT_KERNEL_TIMEX_PTR, 0, 0, 0, 0, 0, 0},
    {"mprotect", VOID_PTR, SIZE_T, UNSIGNED_LONG, 0, 0, 0, 0},
    {"sigprocmask", INT, OLD_SIGSET_T_PTR, OLD_SIGSET_T_PTR, 0, 0, 0, 0},
    {"create_module", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"init_module", VOID_PTR, UNSIGNED_LONG, CONST_CHAR_PTR, 0, 0, 0, 0},
    {"delete_module", CONST_CHAR_PTR, UNSIGNED_INT, 0, 0, 0, 0, 0},
    {"get_kernel_syms", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"quotactl", UNSIGNED_INT, CONST_CHAR_PTR, QID_T, VOID_PTR, 0, 0, 0},
    {"getpgid", PID_T, 0, 0, 0, 0, 0, 0},
    {"fchdir", UNSIGNED_INT, 0, 0, 0, 0, 0, 0},
    {"bdflush", INT, LONG, 0, 0, 0, 0, 0},
    {"sysfs", INT, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0, 0, 0},
    {"personality", UNSIGNED_INT, 0, 0, 0, 0, 0, 0},
    {"afs_syscall", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setfsuid", UID_T, 0, 0, 0, 0, 0, 0},
    {"setfsgid", GID_T, 0, 0, 0, 0, 0, 0},
    {"_llseek", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"getdents", UNSIGNED_INT, STRUCT_LINUX_DIRENT_PTR, UNSIGNED_INT, 0, 0, 0, 0},
    {"_newselect", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"flock", UNSIGNED_INT, UNSIGNED_INT, 0, 0, 0, 0, 0},
    {"msync", UNSIGNED_LONG, SIZE_T, INT, 0, 0, 0, 0},
    {"readv", UNSIGNED_LONG, STRUCT_IOVEC_PTR, UNSIGNED_LONG, 0, 0, 0, 0},
    {"writev", UNSIGNED_LONG, STRUCT_IOVEC_PTR, UNSIGNED_LONG, 0, 0, 0, 0},
    {"getsid", PID_T, 0, 0, 0, 0, 0, 0},
    {"fdatasync", UNSIGNED_INT, 0, 0, 0, 0, 0, 0},
    {"_sysctl", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"mlock", UNSIGNED_LONG, SIZE_T, 0, 0, 0, 0, 0},
	{"munlock", UNSIGNED_LONG, SIZE_T, 0, 0, 0, 0, 0},
    {"mlockall", INT, 0, 0, 0, 0, 0, 0},
    {"munlockall", 0, 0, 0, 0, 0, 0, 0},
    {"sched_setparam", PID_T, STRUCT_SCHED_PARAM_PTR, 0, 0, 0, 0, 0},
    {"sched_getparam", PID_T, STRUCT_SCHED_PARAM_PTR, 0, 0, 0, 0, 0},
    {"sched_setscheduler", PID_T, INT, STRUCT_SCHED_PARAM_PTR, 0, 0, 0, 0},
    {"sched_getscheduler", PID_T, 0, 0, 0, 0, 0, 0},
    {"sched_yield", 0, 0, 0, 0, 0, 0, 0},
    {"sched_get_priority_max", INT, 0, 0, 0, 0, 0, 0},
    {"sched_get_priority_min", INT, 0, 0, 0, 0, 0, 0},
    {"sched_rr_get_interval", PID_T, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0, 0, 0},
    {"nanosleep", STRUCT_KERNEL_TIMESPEC_PTR, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0, 0, 0},
    {"mremap", UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"setresuid", UID_T, UID_T, UID_T, 0, 0, 0, 0},
    {"getresuid", UID_T_PTR, UID_T_PTR, UID_T_PTR, 0, 0, 0, 0},
    {"vm86", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"query_module", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"poll", STRUCT_POLLFD_PTR, UNSIGNED_INT, INT, 0, 0, 0, 0},
    {"nfsservctl", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setresgid", GID_T, GID_T, GID_T, 0, 0, 0, 0},
    {"getresgid", GID_T_PTR, GID_T_PTR, GID_T_PTR, 0, 0, 0, 0},
    {"prctl", INT, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"rt_sigreturn", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"rt_sigaction", INT, STRUCT_SIGACTION_PTR, STRUCT_SIGACTION_PTR, SIZE_T, 0, 0, 0},
    {"rt_sigprocmask", INT, SIGSET_T_PTR, SIGSET_T_PTR, SIZE_T, 0, 0, 0},
    {"rt_sigpending", SIGSET_T_PTR, SIZE_T, 0, 0, 0, 0, 0},
    {"rt_sigtimedwait", CONST_SIGSET_T_PTR, SIGINFO_T_PTR, CONST_STRUCT_KERNEL_TIMESPEC_PTR, SIZE_T, 0, 0, 0},
    {"rt_sigqueueinfo", PID_T, INT, SIGINFO_T_PTR, 0, 0, 0, 0},
    {"rt_sigsuspend", SIGSET_T_PTR, SIZE_T, 0, 0, 0, 0, 0},
    {"pread64", UNSIGNED_INT, CHAR_PTR, SIZE_T, LOFF_T, 0, 0, 0},
    {"pwrite64", UNSIGNED_INT, CONST_CHAR_PTR, SIZE_T, LOFF_T, 0, 0, 0},
    {"chown", CONST_CHAR_PTR, UID_T, GID_T, 0, 0, 0, 0},
    {"getcwd", CHAR_PTR, UNSIGNED_LONG, 0, 0, 0, 0, 0},
    {"capget", CAP_USER_HEADER_T, CAP_USER_DATA_T, 0, 0, 0, 0, 0},
    {"capset", CAP_USER_HEADER_T, CONST_CAP_USER_DATA_T, 0, 0, 0, 0, 0},
    {"sigaltstack", CONST_STRUCT_SIGALTSTACK_PTR, STRUCT_SIGALTSTACK_PTR, 0, 0, 0, 0, 0},
    {"sendfile", INT, INT, LOFF_T_PTR, SIZE_T, 0, 0, 0},
    {"getpmsg", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"putpmsg", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"vfork", 0, 0, 0, 0, 0, 0, 0},
    {"ugetrlimit", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"mmap2", VOID_PTR, SIZE_T, INT, INT, INT, OFF_T, 1},
    {"truncate64", CONST_CHAR_PTR, LOFF_T, 0, 0, 0, 0, 0},
    {"ftruncate64", UNSIGNED_INT, LOFF_T, 0, 0, 0, 0, 0},
    {"stat64", CONST_CHAR_PTR, STRUCT_STAT64_PTR, 0, 0, 0, 0, 0},
    {"lstat64", CONST_CHAR_PTR, STRUCT_STAT64_PTR, 0, 0, 0, 0, 0},
    {"fstat64", UNSIGNED_LONG, STRUCT_STAT64_PTR, 0, 0, 0, 0, 0},
    {"lchown32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"getuid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"getgid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
	{"geteuid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"getegid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setreuid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setregid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"getgroups32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setgroups32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"fchown32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setresuid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"getresuid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setresgid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"getresgid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"chown32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setuid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setgid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setfsuid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"setfsgid32", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"pivot_root", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"mincore", UNSIGNED_LONG, SIZE_T, UNSIGNED_CHAR_PTR, 0, 0, 0, 0},
    {"madvise", UNSIGNED_LONG, SIZE_T, INT, 0, 0, 0, 0},
    {"getdents64", UNSIGNED_INT, STRUCT_LINUX_DIRENT64_PTR, UNSIGNED_INT, 0, 0, 0, 0},
    {"fcntl64", UNSIGNED_INT, UNSIGNED_INT, UNSIGNED_LONG, 0, 0, 0, 0},
    {"not_implemented", 0, 0, 0, 0, 0, 0, 0},
    {"not_implemented", 0, 0, 0, 0, 0, 0, 0},
    {"gettid", 0, 0, 0, 0, 0, 0, 0},
    {"readahead", INT, LOFF_T, SIZE_T, 0, 0, 0, 0},
    {"setxattr", CONST_CHAR_PTR, CONST_CHAR_PTR, CONST_VOID_PTR, SIZE_T, INT, 0, 0},
    {"lsetxattr", CONST_CHAR_PTR, CONST_CHAR_PTR, CONST_VOID_PTR, SIZE_T, INT, 0, 0},
    {"fsetxattr", INT, CONST_CHAR_PTR, CONST_VOID_PTR, SIZE_T, INT, 0, 0},
    {"getxattr", CONST_CHAR_PTR, CONST_CHAR_PTR, VOID_PTR, SIZE_T, 0, 0, 0},
    {"lgetxattr", CONST_CHAR_PTR, CONST_CHAR_PTR, VOID_PTR, SIZE_T, 0, 0, 0},
    {"fgetxattr", INT, CONST_CHAR_PTR, VOID_PTR, SIZE_T, 0, 0, 0},
    {"listxattr", CONST_CHAR_PTR, CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"llistxattr", CONST_CHAR_PTR, CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"flistxattr", INT, CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"removexattr", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"lremovexattr", CONST_CHAR_PTR, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"fremovexattr", INT, CONST_CHAR_PTR, 0, 0, 0, 0, 0},
    {"tkill", PID_T, INT, 0, 0, 0, 0, 0},
    {"sendfile64", INT, INT, LOFF_T_PTR, SIZE_T, 0, 0, 0},
    {"futex", U32_PTR, INT, U32, STRUCT_KERNEL_TIMESPEC_PTR, U32_PTR, U32, 0},
    {"sched_setaffinity", PID_T, UNSIGNED_INT, UNSIGNED_LONG_PTR, 0, 0, 0, 0},
    {"sched_getaffinity", PID_T, UNSIGNED_INT, UNSIGNED_LONG_PTR, 0, 0, 0, 0},
    {"set_thread_area", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"get_thread_area", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"io_setup", UNSIGNED, AIO_CONTEXT_T_PTR, 0, 0, 0, 0, 0},
    {"io_destroy", AIO_CONTEXT_T, 0, 0, 0, 0, 0, 0},
    {"io_getevents", AIO_CONTEXT_T, LONG, LONG, STRUCT_IO_EVENT_PTR, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0},
    {"io_submit", AIO_CONTEXT_T, LONG, STRUCT_IOCB_PTR_PTR, 0, 0, 0, 0},
    {"io_cancel", AIO_CONTEXT_T, STRUCT_IOCB_PTR, STRUCT_IO_EVENT_PTR, 0, 0, 0, 0},
    {"fadvise64", INT, LOFF_T, SIZE_T, INT, 0, 0, 0},
	{"not_implemented", 0, 0, 0, 0, 0, 0, 0},
    {"exit_group", INT, 0, 0, 0, 0, 0, 0},
    {"lookup_dcookie", U64, CHAR_PTR, SIZE_T, 0, 0, 0, 0},
    {"epoll_create", INT, 0, 0, 0, 0, 0, 0},
    {"epoll_ctl", INT, INT, INT, STRUCT_EPOLL_EVENT_PTR, 0, 0, 0},
    {"epoll_wait", INT, STRUCT_EPOLL_EVENT_PTR, INT, INT, 0, 0, 0},
    {"remap_file_pages", UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"set_tid_address", INT_PTR, 0, 0, 0, 0, 0, 0},
    {"timer_create", CLOCKID_T, STRUCT_SIGEVENT_PTR, TIMER_T_PTR, 0, 0, 0, 0},
    {"timer_settime", TIMER_T, INT, STRUCT_KERNEL_ITIMERSPEC_PTR, STRUCT_KERNEL_ITIMERSPEC_PTR, 0, 0, 0},
    {"timer_gettime", TIMER_T, STRUCT_KERNEL_ITIMERSPEC_PTR, 0, 0, 0, 0, 0},
    {"timer_getoverrun", TIMER_T, 0, 0, 0, 0, 0, 0},
    {"timer_delete", TIMER_T, 0, 0, 0, 0, 0, 0},
    {"clock_settime", CLOCKID_T, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0, 0, 0},
    {"clock_gettime", CLOCKID_T, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0, 0, 0},
    {"clock_getres", CLOCKID_T, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0, 0, 0},
    {"clock_nanosleep", CLOCKID_T, INT, STRUCT_KERNEL_TIMESPEC_PTR, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0, 0},
    {"statfs64", CONST_CHAR_PTR, SIZE_T, STRUCT_STATFS64_PTR, 0, 0, 0, 0},
    {"fstatfs64", UNSIGNED_INT, SIZE_T, STRUCT_STATFS64_PTR, 0, 0, 0, 0},
    {"tgkill", PID_T, PID_T, INT, 0, 0, 0, 0},
    {"utimes", CHAR_PTR, STRUCT_TIMEVAL_PTR, 0, 0, 0, 0, 0},
    {"fadvise64_64", INT, LOFF_T, LOFF_T, INT, 0, 0, 0},
    {"vserver", 0, 0, 0, 0, 0, 0, 0},
    {"mbind", UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, CONST_UNSIGNED_LONG_PTR, UNSIGNED_LONG, UNSIGNED, 0},
    {"get_mempolicy", INT_PTR, UNSIGNED_LONG_PTR, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"set_mempolicy", INT, CONST_UNSIGNED_LONG_PTR, UNSIGNED_LONG, 0, 0, 0, 0},
    {"mq_open", CONST_CHAR_PTR, INT, UMODE_T, STRUCT_MQ_ATTR_PTR, 0, 0, 0},
    {"mq_unlink", CONST_CHAR_PTR, 0, 0, 0, 0, 0, 0},
    {"mq_timedsend", MQD_T, CONST_CHAR_PTR, SIZE_T, UNSIGNED_INT, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0},
    {"mq_timedreceive", MQD_T, CHAR_PTR, SIZE_T, UNSIGNED_INT_PTR, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0},
    {"mq_notify", MQD_T, STRUCT_SIGEVENT_PTR, 0, 0, 0, 0, 0},
    {"mq_getsetattr", MQD_T, STRUCT_MQ_ATTR_PTR, STRUCT_MQ_ATTR_PTR, 0, 0, 0, 0},
    {"kexec_load", UNSIGNED_LONG, UNSIGNED_LONG, STRUCT_KEXEC_SEGMENT_PTR, UNSIGNED_LONG, 0, 0, 0},
    {"waitid", INT, PID_T, STRUCT_SIGINFO_PTR, INT, STRUCT_RUSAGE_PTR, 0, 0},
    {"not_implemented", 0, 0, 0, 0, 0, 0, 0},
    {"add_key", CONST_CHAR_PTR, CONST_CHAR_PTR, CONST_VOID_PTR, SIZE_T, KEY_SERIAL_T, 0, 0},
    {"request_key", CONST_CHAR_PTR, CONST_CHAR_PTR, CONST_CHAR_PTR, KEY_SERIAL_T, 0, 0, 0},
    {"keyctl", INT, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"ioprio_set", INT, INT, INT, 0, 0, 0, 0},
    {"ioprio_get", INT, INT, 0, 0, 0, 0, 0},
    {"inotify_init", 0, 0, 0, 0, 0, 0, 0},
    {"inotify_add_watch", INT, CONST_CHAR_PTR, U32, 0, 0, 0, 0},
    {"inotify_rm_watch", INT, INT, 0, 0, 0, 0, 0},
    {"migrate_pages", PID_T, UNSIGNED_LONG, CONST_UNSIGNED_LONG_PTR, CONST_UNSIGNED_LONG_PTR, 0, 0, 0},
    {"openat", INT, CONST_CHAR_PTR, INT, UMODE_T, 0, 0, 0},
    {"mkdirat", INT, CONST_CHAR_PTR, UMODE_T, 0, 0, 0, 0},
    {"mknodat", INT, CONST_CHAR_PTR, UMODE_T, UNSIGNED, 0, 0, 0},
    {"fchownat", INT, CONST_CHAR_PTR, UID_T, GID_T, INT, 0, 0},
    {"futimesat", INT, CONST_CHAR_PTR, STRUCT_TIMEVAL_PTR, 0, 0, 0, 0},
    {"fstatat64", INT, CONST_CHAR_PTR, STRUCT_STAT64_PTR, INT, 0, 0, 0},
	{"unlinkat", INT, CONST_CHAR_PTR, INT, 0, 0, 0, 0},
    {"renameat", INT, CONST_CHAR_PTR, INT, CONST_CHAR_PTR, 0, 0, 0},
    {"linkat", INT, CONST_CHAR_PTR, INT, CONST_CHAR_PTR, INT, 0, 0},
    {"symlinkat", CONST_CHAR_PTR, INT, CONST_CHAR_PTR, 0, 0, 0, 0},
    {"readlinkat", INT, CONST_CHAR_PTR, CHAR_PTR, INT, 0, 0, 0},
    {"fchmodat", INT, CONST_CHAR_PTR, UMODE_T, 0, 0, 0, 0},
    {"faccessat", INT, CONST_CHAR_PTR, INT, 0, 0, 0, 0},
    {"pselect6", INT, FD_SET_PTR, FD_SET_PTR, FD_SET_PTR, STRUCT_KERNEL_TIMESPEC_PTR, VOID_PTR, 0},
    {"ppoll", STRUCT_POLLFD_PTR, UNSIGNED_INT, STRUCT_KERNEL_TIMESPEC_PTR, SIGSET_T_PTR, SIZE_T, 0, 0},
    {"unshare", UNSIGNED_LONG, 0, 0, 0, 0, 0, 0},
    {"set_robust_list", STRUCT_ROBUST_LIST_HEAD_PTR, SIZE_T, 0, 0, 0, 0, 0},
    {"get_robust_list", INT, STRUCT_ROBUST_LIST_HEAD_PTR_PTR, SIZE_T_PTR, 0, 0, 0, 0},
    {"splice", INT, LOFF_T_PTR, INT, LOFF_T_PTR, SIZE_T, UNSIGNED_INT, 0},
    {"sync_file_range", INT, LOFF_T, LOFF_T, UNSIGNED_INT, 0, 0, 0},
    {"tee", INT, INT, SIZE_T, UNSIGNED_INT, 0, 0, 0},
    {"vmsplice", INT, CONST_STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_INT, 0, 0, 0},
    {"move_pages", PID_T, UNSIGNED_LONG, CONST_VOID_PTR_PTR, CONST_INT_PTR, INT_PTR, INT, 0},
    {"getcpu", UNSIGNED_PTR, UNSIGNED_PTR, STRUCT_GETCPU_CACHE_PTR, 0, 0, 0, 0},
    {"epoll_pwait", INT, STRUCT_EPOLL_EVENT_PTR, INT, INT, STRUCT_KERNEL_TIMESPEC_PTR, SIZE_T, 0},
    {"utimensat", INT, CONST_CHAR_PTR, STRUCT_KERNEL_TIMESPEC_PTR, INT, 0, 0, 0},
    {"signalfd", INT, SIGSET_T_PTR, SIZE_T, 0, 0, 0, 0},
    {"timerfd_create", INT, INT, 0, 0, 0, 0, 0},
    {"eventfd", UNSIGNED_INT, 0, 0, 0, 0, 0, 0},
    {"fallocate", INT, INT, LOFF_T, LOFF_T, 0, 0, 0},
    {"timerfd_settime", INT, INT, CONST_STRUCT_KERNEL_ITIMERSPEC_PTR, STRUCT_KERNEL_ITIMERSPEC_PTR, 0, 0, 0},
    {"timerfd_gettime", INT, STRUCT_KERNEL_ITIMERSPEC_PTR, 0, 0, 0, 0, 0},
    {"signalfd4", INT, SIGSET_T_PTR, SIZE_T, INT, 0, 0, 0},
    {"eventfd2", UNSIGNED_INT, INT, 0, 0, 0, 0, 0},
    {"epoll_create1", INT, INT, 0, 0, 0, 0, 0},
    {"dup3", UNSIGNED_INT, UNSIGNED_INT, INT, 0, 0, 0, 0},
    {"pipe2", INT_PTR, INT, 0, 0, 0, 0, 0},
    {"inotify_init1", INT, 0, 0, 0, 0, 0, 0},
    {"preadv", UNSIGNED_LONG, CONST_STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"pwritev", UNSIGNED_LONG, CONST_STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"rt_tgsigqueueinfo", PID_T, PID_T, INT, STRUCT_SIGINFO_PTR, 0, 0, 0},
    {"perf_event_open", STRUCT_PERF_EVENT_ATTR_PTR, PID_T, INT, INT, UNSIGNED_LONG, 0, 0},
    {"recvmmsg", INT, STRUCT_MMSGHDR_PTR, UNSIGNED_INT, UNSIGNED, STRUCT_KERNEL_TIMESPEC_PTR, 0, 0},
    {"fanotify_init", UNSIGNED_INT, UNSIGNED_INT, 0, 0, 0, 0, 0},
    {"fanotify_mark", INT, UNSIGNED_INT, U64, INT, CONST_CHAR_PTR, 0, 0},
    {"prlimit64", PID_T, UNSIGNED_INT, CONST_STRUCT_RLIMIT64_PTR, STRUCT_RLIMIT64_PTR, 0, 0, 0},
    {"name_to_handle_at", INT, CONST_CHAR_PTR, STRUCT_FILE_HANDLE_PTR, INT_PTR, INT, 0, 0},
    {"open_by_handle_at", INT, STRUCT_FILE_HANDLE_PTR, INT, 0, 0, 0, 0},
    {"clock_adjtime", CLOCKID_T, STRUCT_KERNEL_TIMEX_PTR, 0, 0, 0, 0, 0},
    {"syncfs", INT, 0, 0, 0, 0, 0, 0},
    {"sendmmsg", INT, STRUCT_MMSGHDR_PTR, UNSIGNED_INT, UNSIGNED, 0, 0, 0},
    {"setns", INT, INT, 0, 0, 0, 0, 0},
    {"process_vm_readv", PID_T, CONST_STRUCT_IOVEC_PTR, UNSIGNED_LONG, CONST_STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, 0},
    {"process_vm_writev", PID_T, CONST_STRUCT_IOVEC_PTR, UNSIGNED_LONG, CONST_STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, 0},
    {"kcmp", PID_T, PID_T, INT, UNSIGNED_LONG, UNSIGNED_LONG, 0, 0},
    {"finit_module", INT, CONST_CHAR_PTR, INT, 0, 0, 0, 0},
	{"sched_setattr", PID_T, STRUCT_SCHED_ATTR_PTR, UNSIGNED_INT, 0, 0, 0, 0},
    {"sched_getattr", PID_T, STRUCT_SCHED_ATTR_PTR, UNSIGNED_INT, UNSIGNED_INT, 0, 0, 0},
    {"renameat2", INT, CONST_CHAR_PTR, INT, CONST_CHAR_PTR, UNSIGNED_INT, 0, 0},
    {"seccomp", UNSIGNED_INT, UNSIGNED_INT, VOID_PTR, 0, 0, 0, 0},
    {"getrandom", CHAR_PTR, SIZE_T, UNSIGNED_INT, 0, 0, 0, 0},
    {"memfd_create", CONST_CHAR_PTR, UNSIGNED_INT, 0, 0, 0, 0, 0},
    {"bpf", INT, UNION_BPF_ATTR_PTR, UNSIGNED_INT, 0, 0, 0, 0},
    {"execveat", INT, CONST_CHAR_PTR, CONST_CHAR_PTR_PTR, CONST_CHAR_PTR_PTR, INT, 0, 0},
    {"socket", INT, INT, INT, 0, 0, 0, 0},
    {"socketpair", INT, INT, INT, INT_PTR, 0, 0, 0},
    {"bind", INT, STRUCT_SOCKADDR_PTR, INT, 0, 0, 0, 0},
    {"connect", INT, STRUCT_SOCKADDR_PTR, INT, 0, 0, 0, 0},
    {"listen", INT, INT, 0, 0, 0, 0, 0},
    {"accept4", INT, STRUCT_SOCKADDR_PTR, INT_PTR, INT, 0, 0, 0},
    {"getsockopt", INT, INT, INT, CHAR_PTR, INT_PTR, 0, 0},
    {"setsockopt", INT, INT, INT, CHAR_PTR, INT, 0, 0},
    {"getsockname", INT, STRUCT_SOCKADDR_PTR, INT_PTR, 0, 0, 0, 0},
    {"getpeername", INT, STRUCT_SOCKADDR_PTR, INT_PTR, 0, 0, 0, 0},
    {"sendto", INT, VOID_PTR, SIZE_T, UNSIGNED, STRUCT_SOCKADDR_PTR, INT, 0},
    {"sendmsg", INT, STRUCT_USER_MSGHDR_PTR, UNSIGNED, 0, 0, 0, 0},
    {"recvfrom", INT, VOID_PTR, SIZE_T, UNSIGNED, STRUCT_SOCKADDR_PTR, INT_PTR, 0},
    {"recvmsg", INT, STRUCT_USER_MSGHDR_PTR, UNSIGNED, 0, 0, 0, 0},
    {"shutdown", INT, INT, 0, 0, 0, 0, 0},
    {"userfaultfd", INT, 0, 0, 0, 0, 0, 0},
    {"membarrier", INT, INT, 0, 0, 0, 0, 0},
    {"mlock2", UNSIGNED_LONG, SIZE_T, INT, 0, 0, 0, 0},
    {"copy_file_range", INT, LOFF_T_PTR, INT, LOFF_T_PTR, SIZE_T, UNSIGNED_INT, 0},
    {"preadv2", UNSIGNED_LONG, CONST_STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, RWL_T, 0},
    {"pwritev2", UNSIGNED_LONG, CONST_STRUCT_IOVEC_PTR, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, RWL_T, 0},
    {"pkey_mprotect", VOID_PTR, SIZE_T, UNSIGNED_LONG, INT, 0, 0, 0},
    {"pkey_alloc", UNSIGNED_LONG, UNSIGNED_LONG, 0, 0, 0, 0, 0},
    {"pkey_free", INT, 0, 0, 0, 0, 0, 0},
    {"statx", INT, CONST_CHAR_PTR, UNSIGNED, UNSIGNED, STRUCT_STATX_PTR, 0, 0},
    {"arch_prctl", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
    {"????", UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, 0},
	{"rseq", STRUCT_RSEQ, U32, INT, U32, 0, 0, 0}
};

#endif
